python/study_py/django/learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),
]

python/study_py/django/learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url
from . import views

urlpatterns = [
# 主页
	url(r'^$', views.index, name='index'),
	# 显示所有的主题
	url(r'^topics/$', views.topics, name='topics'),
	# 特定主题的详细页面
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	# 用于添加新主题的网页
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	# 用于添加新条目的页面
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	# 用于编辑条目的页面
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,name='edit_entry'),
]

python/study_py/django/users/urls.py
"""为应用程序users定义URL模式"""
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
	# 登录页面
	url(r'^login/$',login, {'template_name':'users/login.html'},name='login'),
]

python/study_py/django/learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """user leraning Topic"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
    	"""reutrn Modle str"""
    	return self.text
    	


class Entry(models.Model):
	"""学到的有关某个主题的具体知识"""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""返回模型的字符串表示"""
		# if(sizeof(self.text) > 50):
			# return self.text[:50] + "..."
		#  else:
		#  return self.text[:50]
		return self.text[:50] + "..."

python/study_py/django/users/models.py
from django.db import models

# Create your models here.

python/study_py/django/learning_logs/forms.py
from django import forms
from .models import Topic
from .models import Topic, Entry

#forms.py

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text':''}
		
class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text':''}
		widgets = {'text':forms.Textarea(attrs = {'cols':80})}

python/study_py/django/learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import TopicForm,EntryForm
import datetime


# Create your views here.
def index(request):
	"""学习笔记的主页"""
	now = datetime.datetime.now()
	context = {'datetime':now}
	return render(request,'learning_logs/index.html',context)

def topics(request):
	"""显示所有的主题"""
	topics = Topic.objects.order_by('date_added')
	context = {'topics':topics}
	return render(request,'learning_logs/topics.html',context)

def topic(request, topic_id):
	"""显示单个主题及其所有的条目"""
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		# 未提交数据：创建一个新表单
		form = TopicForm()
	else :
		# POST提交的数据,对数据进行处理
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))

	context = {'form':form}
	return render(request,'learning_logs/new_topic.html',context)


def new_entry(request,topic_id):
	"""在特定的主题中添加新条目"""
	topic = Topic.objects.get(id = topic_id)

	if request.method != 'POST':
		# 未提交数据,创建一个空表单
		form = EntryForm()
	else:
		# POST提交的数据,对数据进行处理
		form = EntryForm(data = request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

	context = {'topic':topic,'form':form}
	return render(request,'learning_logs/new_entry.html',context)

def edit_entry(request,entry_id):
	"""编辑既有条目"""
	entry = Entry.objects.get(id = entry_id)
	topic = entry.topic

	if request.method != 'POST':
		# 初次请求，使用当前条目填充表单
		form = EntryForm(instance = entry)
	else:
		# POST提交的数据，对数据进行处理
		form = EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
	context = {'entry':entry,'topic':topic,'form':form}
	return render(request,'learning_logs/edit_entry.html',context)

python/study_py/django/users/views.py
from django.shortcuts import render

# Create your views here.

python/study_py/django/learning_logs/templates/learning_logs/base.html
<!-- <link rel="stylesheet" href="/opt/git_Atom/study/python/study_py/django/learning_logs/templates/learning_logs/font-awesome/css/font-awesome.min.css"> -->
<!-- <link rel="stylesheet" href="./font-awesome/css/font-awesome.min.css"> -->
<link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
                        
                        
<!-- <i class="fa fa-camera-retro"></i> -->
<p>
	<a href="{% url 'learning_logs:index'%}">Learning Log</a> -
	<a href="{% url 'learning_logs:topics' %}">Topics</a> -
	{% if user.is_authenticated %}
		Hello,{{user.username}}.
	{% else %}
		<a href="{% url 'users:login'%}">log in </a>
	{% endif %}
</p>

{%block content %}{%endblock content%}

python/study_py/django/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>
	<p>Edit entry:</p>

	<form action="{% url 'learning_logs:edit_entry' entry.id%}" method='post'>
		{% csrf_token %}
		{{form.as_p}}
		<button name="submit">Save changes</button>		
	</form>

{% endblock content %}

python/study_py/django/learning_logs/templates/learning_logs/index.html
<!---->
{% extends "learning_logs/base.html" %} <!--继承-->

{% block content %}  <!--块预留的空间中添加的内容-->
	<p>Learning Log helps you keep track of your learning, for any topic you're learning about.</p>
	<p> {{datetime}}</p>
{% endblock content %}


<!--<p>Learning Log</p>

<p>Learning Log helps you keep track of your learning, for any topic you'relearning about.</p>-->

python/study_py/django/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{%block content%}
	<p><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></p>

	<p>Add a new entry:</p>
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST'>
		{% csrf_token %}
		{{form.as_p}}
		<button name='submit'>add entry</button>
	</form>

{%endblock content%}

python/study_py/django/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{%block content %}
	<p>Add a new topic :</p>

	<form action="{%url 'learning_logs:new_topic'%}" method='post'>
		{% csrf_token %}
		{{form.as_p}}
		<button name="submit">add topic</button>
	</form>

{%endblock content%}

python/study_py/django/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
	<p>Topic:{{ topic }}</p>

	<p>Entries:</p>
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
	</p>
	<ur>
	{%for entry in entries%}
		<li>
			<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
			<p>{{ entry.text|linebreaks }}</p>
			<p>
				<a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
			</p>
		</li>
	{% empty %}
		<li>
			There are no entries for this topic yet.
		</li>
{% endfor %}

	</ur>

{% endblock content %}

python/study_py/django/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html"%}

{% block content %}
	<p>Topics</p>
	<ul>
		{% for topic in topics %}
			<li>
			<!-- {{ topic }} -->
			<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
			</li>
		{% empty %}
			<li>No topics have been added yet.</li>
		{% endfor %}
	</ul>
	<a href="{% url 'learning_logs:new_topic'%}">Add a new topic</a>

{% endblock content %}

python/study_py/django/users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block content %}
	{% if form.errors %}
	<p> Your username and passwd didn`t match. Plase try again.</p>
	{% endif %}

	<form method="post" action="{% url 'users:login' %}">	
	{% csrf_token %}
	{{form.as_p}}

	<button name="submit">log in</button>
	<input type="hidden" name="next" value="{% url 'learnings_logs:indix'%}"/>
	</form>


{% endblock content%}